version: '3.7'
services:

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=apiuser
      - POSTGRES_PASSWORD=apipassword
      - POSTGRES_DB=urlshortener
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U apiuser -d urlshortener"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
volumes:
  postgres_data:
